### ISSUE TITLE
Need Help theming and Compiling

### ISSUE THREAD

**Issue by JayBenjamin** [nextcloud/windows-universal#153]
I'm afraid the only issue here may be me. I'm trying to theme and compile a working version of this that synchronizes the files in the clients' directory. I don't know where to start and would love some help or for someone to do it for me. The web side of things are already setup. Freelancer.com, unfortunately didn't pan out and my deadline for this project is on Monday :) Can anyone help and since this isn't a real issue, where should I have posted this?

**Comment by SunboX** [comment]
That's not how Open Source Software works. If you have no clue how this app works - please pay someone who has. 😏 Especially, if you do not want to help devoping this further and "just" want to adapt it for your own needs. I'm always open to help someone who want's to help the community (as far as my little spare time allows it). But for your needs, you have to pay someone - maybe a freelancer. 😏 

I will close this, because it's not an issue.

**Comment by JayBenjamin** [comment]
Do any good freelancers come to mind?

**Comment by SunboX** [comment]
No, sorry, don't know someone. Just employed people. Maybe you can find someone in the numerous online portals (like https://www.mylittlejob.de/?benutzer_language=en).
