### ISSUE TITLE
Removing translation resource from Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/windows-universal#272]
The app looks deprecated.
So I would like to remove the resource from Transifex.

If you ask why? See https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312

@MorrisJobke @rullzer Are there any objections on your part?

btw. No action needed from your side. My rights at Transifex are sufficient to do this.

**Comment by SunboX** [comment]
Hey,

feel free. Because of missing Windows Phone and my switch from C# to TypeScript/Universal AppBuilding I have no time and setup anymore to work on this project. Sadly.

I tried many times to find a maintainer for this project, because the source is great and it is a good base for a Nextcloud Client for Windows Universal - but I could not find anyone. If you get one - let me know, I will handover everything to him.

greetings and thx,
André
________________________________

**Comment by rakekniven** [comment]
Ok, I will remove it.
Existing translations are not lost.

**Comment by MorrisJobke** [comment]
@rakekniven Before removing we also need to disable the transifex bot. Otherwise it will be uploaded directly afterwards. Let me do this.
